// ---------------------------------------------------------
const shuntNormalKeys = (keys) => keys.forEach((key) => map(`!!${key}`, key))
const unmapNormalKeys = (keys) => keys.forEach((key) => unmap(key))
const unshuntNormalKeys = (keys) => keys.forEach((key) => unmap(`!!${key}`))
// ---------------------------------------------------------
const defaultNormalKeys = ["<Alt-s>","<Alt-i>","p",";ql","cf",";m",";fs","O","af","C","<Ctrl-h>","<Ctrl-j>","I","<Ctrl-i>","q","<Ctrl-Alt-i>","cS","cs","j","k",";w","w","yt","yT","g0","g$","gx0","gxt","gxT","gx$","gxx","gxp","E","R","T",";gt",";gw","<Alt-p>","<Alt-m>","on","gT","gt","gp",";u",";U","B","F","<Ctrl-6>","S","D","ZZ","ZR","sg","sd","sb","se","sw","ss","sh","sy","yG","yS","yi","ys","yj","yQ","yp","cq","cc",";pp",";pj","oi","od","ob","oe","H","t","m","'","<Ctrl-'>",";pm",";e",";v","gc","gk","gn",";i",";j","cp",";pa",";pb",";pd",";ps",";pc",";cp",";ap","gr",";s",";ph",";t",";dh",";db",";yh","ZQ"];
shuntNormalKeys(defaultNormalKeys);
unmapNormalKeys(defaultNormalKeys);

map("@@", "!!<Alt-s>")
map("@pt", "!!<Alt-i>")
map("@1pt", "!!p")
map(";F", "!!cf")
map("cf", "!!;fs")
map(";u", "!!O")
map("F", "!!C")
map(";mov", "!!<Ctrl-h>")
map(";mou", "!!<Ctrl-j>")
map(";f", "!!q")
map("cc", "!!cS")
map("c;", "!!cs")
map("j", "!!j")
map("s", "!!j")
map("k", "!!k")
map("w", "!!k")
map("cw;", "!!w")
map("ty", "!!yt")
map("tY", "!!yT")
map("t0", "!!g0")
map("t$", "!!g$")
map("tx0", "!!gx0")
map("txl", "!!gxt")
map("txr", "!!gxT")
map("tx$", "!!gx$")
map("txx", "!!gxx")
map("txp", "!!gxp")
map("E", "!!E")
map("J", "!!E")
map("R", "!!R")
map("K", "!!R")
map("tgt", "!!;gt")
map("tgw", "!!;gw")
map("tp", "!!<Alt-p>")
map("tm", "!!<Alt-m>")
map("tn", "!!on")
map("tgp", "!!gp")
map("t;", "!!<Ctrl-6>")
map("S", "!!S")
map("H", "!!S")
map("D", "!!D")
map("L", "!!D")
map("y@e", "!!yj")
map(";q", "!!cq")
map("@re", "!!;pj")
map("gp", "!!oi")
map("oH", "!!H")
map("a", "!!t")
map("@mk", "!!m")
map("m", "!!'")
map("M", "!!<Ctrl-'>")
map("@md", "!!;pm")
map("@e", "!!;e")
map("gj", "!!;j")
map("@R", "!!gr")
map("@pdf", "!!;s")
map("@ph", "!!;ph")
map("@t", "!!;t")
map("@yh", "!!;yh")

unshuntNormalKeys(defaultNormalKeys);
// ---------------------------------------------------------
